# Generated by Django 5.0.4 on 2024-07-16 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('passport_serial_number', models.CharField(max_length=9, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
