# Generated by Django 5.0.4 on 2024-07-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='finished_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='started_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_time',
        ),
    ]
