# Generated by Django 5.0.4 on 2024-07-15 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='certificate_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Question.certificate'),
            preserve_default=False,
        ),
    ]
