# Generated by Django 5.0.4 on 2024-07-15 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_certificate_user_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
