# Generated by Django 5.0.4 on 2024-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_remove_user_finished_time_remove_user_started_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wrong_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
