# Generated by Django 5.0.4 on 2024-07-15 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_alter_user_certificate_id_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
