# Generated by Django 5.0.4 on 2024-07-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
